0. E → F             -> id
1. E → E '+' F       -> VAddOp
2. F → G             -> id
3. F → F '*' G       -> VMultOp
4. G → 'int'         -> VInt
5. G → '(' E ')'     -> id

   | Action ----- | ------------ | --- | ----- | ------------ | ------------ | Goto | -- | -- |
IS | '$'          | ')'          | '(' | 'int' | '*'          | '+'          | E    | F  | G  |
0  |              |              | s5  | s4    |              |              | 3    | 2  | 1  |
1  | r(F → G)     | r(F → G)     |     |       | r(F → G)     | r(F → G)     |      |    |    |
2  | r(E → F)     | r(E → F)     |     |       | s8           | r(E → F)     |      |    |    |
3  | acc          |              |     |       |              | s7           |      |    |    |
4  | r(G → int)   | r(G → int)   |     |       | r(G → int)   | r(G → int)   |      |    |    |
5  |              |              | s5  | s4    |              |              | 6    | 2  | 1  |
6  |              | s11          |     |       |              | s7           |      |    |    |
7  |              |              | s5  | s4    |              |              |      | 10 | 1  |
8  |              |              | s5  | s4    |              |              |      |    | 9  |
9  | r(F → F * G) | r(F → F * G) |     |       | r(F → F * G) | r(F → F * G) |      |    |    |
10 | r(E → E + F) | r(E → E + F) |     |       | s8           | r(E → E + F) |      |    |    |
11 | r(G → ( E )) | r(G → ( E )) |     |       | r(G → ( E )) | r(G → ( E )) |      |    |    |
